services:
  frontend:
    build: frontend
    container_name: drg_tracker_frontend
    ports:
    - "80:80"
  backend:
    build: backend
    container_name: drg_tracker_backend
    environment:
      SECRET_KEY: INSERT_RANDOM_LONG_STRING
      HOSTNAME: INSERT_HOSTNAME
    volumes:
    - ./data/db.sqlite3:/django/db.sqlite3