services:
  frontend:
    build: frontend
    ports:
    - "80:80"
  backend:
    build: backend
    environment:
      SECRET_KEY: INSERT_RANDOM_LONG_STRING
      HOSTNAME: INSERT_HOSTNAME
    volumes:
    - ./data/db.sqlite3:/django/db.sqlite3
    ports:
    - "8000:8000"