# Generated by Django 4.1.2 on 2023-02-05 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('Code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('JSON', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
