# Generated by Django 4.1.2 on 2023-02-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreisteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DCode', models.TextField(blank=True)),
                ('DTi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gruppen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrVon', models.TextField(blank=True)),
                ('GrBis', models.TextField(blank=True, null=True)),
                ('GrTi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KapNr', models.TextField(blank=True)),
                ('KapTi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ebene', models.TextField(blank=True, null=True)),
                ('Ort', models.TextField(blank=True, null=True)),
                ('Art', models.TextField(blank=True, null=True)),
                ('Code', models.TextField(blank=True)),
                ('Seite', models.TextField(blank=True, null=True)),
                ('Titel', models.TextField(blank=True, null=True)),
                ('Viersteller', models.TextField(blank=True, null=True)),
                ('Fünfsteller', models.TextField(blank=True, null=True)),
                ('Sechssteller', models.TextField(blank=True, null=True)),
                ('Para17bd', models.TextField(blank=True, null=True)),
                ('DRG', models.TextField(blank=True, null=True)),
                ('ZusatzK', models.TextField(blank=True, null=True)),
                ('EinmalK', models.TextField(blank=True, null=True)),
                ('DCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.dreisteller')),
                ('GrVon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.gruppen')),
                ('KapNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kapitel')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('Year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Umsteiger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideOld', models.TextField(blank=True, null=True)),
                ('SideNew', models.TextField(blank=True, null=True)),
                ('AutoAnte', models.TextField(blank=True, null=True)),
                ('AutoRetro', models.TextField(blank=True, null=True)),
                ('New', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='New', to='ops.kodes')),
                ('Old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Old', to='ops.kodes')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredLong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kodes')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version')),
            ],
        ),
        migrations.CreateModel(
            name='Preferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kodes')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kodes')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version')),
            ],
        ),
        migrations.AddField(
            model_name='kodes',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version'),
        ),
        migrations.AddField(
            model_name='kapitel',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version'),
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kodes')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version')),
            ],
        ),
        migrations.AddField(
            model_name='gruppen',
            name='KapNr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kapitel'),
        ),
        migrations.AddField(
            model_name='gruppen',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version'),
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kodes')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version')),
            ],
        ),
        migrations.AddField(
            model_name='dreisteller',
            name='GrVon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.gruppen'),
        ),
        migrations.AddField(
            model_name='dreisteller',
            name='KapNr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.kapitel'),
        ),
        migrations.AddField(
            model_name='dreisteller',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.version'),
        ),
    ]
